spring:
  application:
    name: 35_Config_Server_App
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties
          clone-on-start: true
management:
    security:
      enabled: true
   